version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db

  frontend:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  db:
    image: mongo
  